import 'dart:io';
import 'dart:developer' as developer;
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:humana/features/attendance/models/attendance_model.dart';
import 'package:humana/features/attendance/services/attendance_api.dart';

class AttendanceService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<void> checkIn({
    required String userId,
    required String userName,
    required String? companyId,
    required String location,
    required String status,
    required double latitude,
    required double longitude,
    required bool insideOffice,
    required String shiftStart,
    required String shiftEnd,
    required int tolerance,
    File? imageFile,
  }) async {
    String imageUrl = "";

    // 1. Try Upload via Custom API
    if (imageFile != null) {
      developer.log(
        "Attempting upload to Custom API with image: ${imageFile.path}",
        name: 'AttendanceService',
      );
      try {
        final apiResult = await AttendanceApi.checkIn(
          employeeId: userId,
          photo: imageFile,
          latitude: latitude,
          longitude: longitude,
          address: location,
          insideOffice: insideOffice,
          shiftStart: shiftStart,
          shiftEnd: shiftEnd,
          tolerance: tolerance,
        );
        if (apiResult != null && apiResult.isNotEmpty) {
          imageUrl = apiResult;
        }
      } catch (e) {
        developer.log(
          "Custom API upload failed: $e",
          name: 'AttendanceService',
        );
      }

      // 2. Fallback to Supabase Storage if API failed
      if (imageUrl.isEmpty) {
        try {
          final fileName =
              '${userId}_${DateTime.now().millisecondsSinceEpoch}.jpg';
          await _supabase.storage
              .from('attendance_photos')
              .upload(fileName, imageFile);
          imageUrl = _supabase.storage
              .from('attendance_photos')
              .getPublicUrl(fileName);
        } catch (e) {
          developer.log(
            "Supabase upload failed: $e",
            name: 'AttendanceService',
          );
        }
      }
    }

    // 2. Save to Supabase
    final attendance = AttendanceModel(
      id: '', // Generated by DB
      userId: userId,
      userName: userName,
      companyId: companyId,
      checkInTime: DateTime.now(),
      checkInLocation: location,
      checkInImageUrl: imageUrl,
      status: status,
      latitude: latitude,
      longitude: longitude,
    );

    // Remove 'id' from map before insert to let Postgres generate it (if using uuid v4 default)
    // But our Model includes 'id'.
    // If we want returned ID, we follow select().single().
    final dataToInsert = attendance.toJson();
    dataToInsert.remove('id');

    await _supabase.from('attendance').insert(dataToInsert);
  }

  Future<void> checkOut({
    required String attendanceId,
    required String location,
    required double latitude,
    required double longitude,
    File? imageFile,
  }) async {
    // 1. Update Supabase
    // We want to set check_out (TIME) and location (JSONB).
    final now = DateTime.now();
    final checkOutTimeStr =
        "${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}:${now.second.toString().padLeft(2, '0')}";

    // Retrieve current location payload to merge
    final currentLocationData = await _supabase
        .from('attendance')
        .select('location')
        .eq('id', attendanceId)
        .single();

    Map<String, dynamic> locationMap = {};
    if (currentLocationData['location'] != null) {
      locationMap = Map<String, dynamic>.from(currentLocationData['location']);
    }
    locationMap['check_out_address'] = location;
    locationMap['lat'] = latitude;
    locationMap['lng'] = longitude;

    final updateData = <String, dynamic>{
      'check_out': checkOutTimeStr,
      'location': locationMap,
      'status': 'Checked Out',
    };

    // if (breaksModified) {
    //   updateData['breaks'] = breaks;
    // }

    await _supabase
        .from('attendance')
        .update(updateData)
        .eq('id', attendanceId);
  }

  Future<List<AttendanceModel>> getUserAttendance(String userId) async {
    final response = await _supabase
        .from('attendance')
        .select()
        // Map userId to employee_id if that's the column name in DB
        .eq('employee_id', userId)
        .order('date', ascending: false)
        .order('check_in', ascending: false);

    return (response as List<dynamic>)
        .map((e) => AttendanceModel.fromJson(e, e['id']))
        .toList();
  }

  Future<AttendanceModel?> getTodayAttendance(String userId) async {
    final now = DateTime.now();
    final todayStr =
        "${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}";

    final response = await _supabase
        .from('attendance')
        .select()
        .eq('employee_id', userId)
        .eq('date', todayStr)
        .limit(1);

    if (response.isNotEmpty) {
      return AttendanceModel.fromJson(response.first, response.first['id']);
    }
    return null;
  }

  Future<List<AttendanceModel>> getAllAttendance(String companyId) async {
    final response = await _supabase
        .from('attendance')
        .select()
        .eq('company_id', companyId)
        .order('date', ascending: false)
        .order('check_in', ascending: false);

    return (response as List<dynamic>)
        .map((e) => AttendanceModel.fromJson(e, e['id']))
        .toList();
  }

  Stream<List<AttendanceModel>> getAttendanceStream(String companyId) {
    return _supabase
        .from('attendance')
        .stream(primaryKey: ['id'])
        .eq('company_id', companyId)
        .order('date', ascending: false)
        .order('check_in', ascending: false)
        .map((List<Map<String, dynamic>> data) {
          return data.map((e) => AttendanceModel.fromJson(e, e['id'])).toList();
        });
  }

  Future<void> deleteAllUserAttendance(String userId) async {
    await _supabase.from('attendance').delete().eq('employee_id', userId);
  }
}
