import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/leave_request_model.dart';
import '../../auth/models/user_model.dart';

class LeaveService {
  final SupabaseClient _supabase = Supabase.instance.client;

  // ------------------------------------
  // EMPLOYEE FLOW
  // ------------------------------------

  Future<void> submitLeaveRequest({
    required UserModel user,
    required String type,
    required String reason,
    required DateTime startDate,
    required DateTime endDate,
    String? companyId,
  }) async {
    // Validation: Start date <= end date
    if (startDate.isAfter(endDate)) {
      throw Exception("Start date must be before or equal to end date.");
    }

    // Check for overlap
    final existingRequests = await getMyRequests(user.id);
    for (final existing in existingRequests) {
      if (existing.status == 'rejected') continue;

      // Overlap logic: (StartA <= EndB) and (EndA >= StartB)
      final bool overlaps =
          startDate.isBefore(
            existing.endDate.add(const Duration(seconds: 1)),
          ) &&
          endDate.isAfter(
            existing.startDate.subtract(const Duration(seconds: 1)),
          );

      if (overlaps) {
        throw Exception(
          "This request overlaps with an existing ${existing.status} request "
          "(${existing.startDate.day}/${existing.startDate.month} - ${existing.endDate.day}/${existing.endDate.month}).",
        );
      }
    }

    final leave = LeaveRequestModel(
      id: '', // Generated by Postgres
      userId: user.id,
      userName: user.fullName,
      userImageUrl: "https://i.pravatar.cc/150?u=${user.id}",
      companyId: companyId ?? 'default_company',
      type: type,
      reason: reason,
      startDate: startDate,
      endDate: endDate,
      status: 'pending',
      createdAt: DateTime.now(),
    );

    final data = leave.toMap();
    data.remove('id'); // Remove ID so DB generates it

    await _supabase.from('leave_requests').insert(data);
  }

  /// 2. View My Leave Requests
  Future<List<LeaveRequestModel>> getMyRequests(String userId) async {
    final response = await _supabase
        .from('leave_requests')
        .select()
        .eq('employee_id', userId)
        .order('start_date', ascending: false);

    return (response as List<dynamic>)
        .map((e) => LeaveRequestModel.fromMap(e, e['id']))
        .toList();
  }

  /// 3. View Leave Detail
  Future<LeaveRequestModel?> getLeaveDetail(String id) async {
    final response = await _supabase
        .from('leave_requests')
        .select()
        .eq('id', id)
        .maybeSingle(); // Use maybeSingle to handle not found gracefully

    if (response != null) {
      return LeaveRequestModel.fromMap(response, response['id']);
    }
    return null;
  }
}
