import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/overtime_request_model.dart';

class OvertimeService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<void> submitOvertimeRequest({
    required String userId,
    required String userName,
    required DateTime date,
    required int durationMinutes,
    required String reason,
    String? companyId,
  }) async {
    final ot = OvertimeRequestModel(
      id: '', // Generated by DB
      userId: userId,
      userName: userName,
      companyId: companyId ?? 'default_company',
      date: date,
      durationMinutes: durationMinutes,
      reason: reason,
      status: 'pending',
      createdAt: DateTime.now(),
    );

    final data = ot.toMap();
    data.remove('id'); // Let DB handle ID generation

    await _supabase.from('overtime_requests').insert(data);
  }

  Future<List<OvertimeRequestModel>> getMyOvertimeRequests(
    String userId,
  ) async {
    final response = await _supabase
        .from('overtime_requests')
        .select()
        .eq('employee_id', userId)
        .order('overtime_date', ascending: false);

    return (response as List<dynamic>)
        .map((e) => OvertimeRequestModel.fromMap(e, e['id']))
        .toList();
  }
}
