import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/shift_swap_request_model.dart';

class ShiftSwapService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<void> submitShiftSwapRequest({
    required String requesterId,
    required String requesterName,
    required DateTime myShiftDate,
    required DateTime targetShiftDate,
    required String targetUserId,
    required String targetUserName,
    required String reason,
    String? companyId,
  }) async {
    final swap = ShiftSwapRequestModel(
      id: '', // Generated by DB
      requesterId: requesterId,
      requesterName: requesterName,
      companyId: companyId ?? 'default_company',
      myShiftDate: myShiftDate,
      targetUserId: targetUserId,
      targetUserName: targetUserName,
      targetShiftDate: targetShiftDate,
      reason: reason,
      status: 'pending',
      createdAt: DateTime.now(),
    );

    final data = swap.toMap();
    data.remove('id'); // Let DB handle ID generation

    await _supabase.from('shift_swaps').insert(data);
  }

  Future<List<ShiftSwapRequestModel>> getMyShiftSwapRequests(
    String userId,
  ) async {
    final response = await _supabase
        .from('shift_swaps')
        .select()
        .eq('requester_id', userId)
        .order('my_shift_date', ascending: false);

    return (response as List<dynamic>)
        .map((e) => ShiftSwapRequestModel.fromMap(e, e['id']))
        .toList();
  }
}
